### PR TITLE
AJS37 DCS-BIOS Profile

### PR DESCRIPTION
**Pull request by pdmarsh**
Adding new DCS-BIOS lua profile for the AJS-37 Viggen.

### CODE REVIEW

**Comment by jboecker** [comment]
I tried to merge this, but there are a bunch of conflicts because this changeset is not based on any release version (it started somewhere between the 0.6.0 and 0.7.0 releases).

The last commit also includes changes to the JSON files of the A-10C that do not match the Lua file (i.e. when I check out your master branch and run DCS, the content of the A-10C JSON files changes).

I could try to fix this with interactive rebase, but that would end up with a commit tree that is different from yours and we'd have a bunch of conflicts again if you then continue to work from your master branch.

Please create one or more new pull requests (ideally: one per aircraft module) that are based on the current 0.7.1 release.

**Comment by pdmarsh** [comment]
Hi Ian,

Sorry for all of the trouble.  I’m still a bit new to this.  I know what happened to the A-10C JSON files.  I added a formula to my module profile, but of course didn’t post that.  I didn’t think about the fact that the JSON files would be changed.  I’ll remove that formula and remake the JSON files with the latest version of DCS-BIOS.

I had intended to create separate pull requests, but new files were getting posted directly to the existing one.  I am using GitHub Desktop.  I’ll try to figure out how to make individual requests.

Thanks,
Paul

**Comment by pdmarsh** [comment]
Hi Ian,

While updating files I noticed that although the L-39ZA profile is included in the latest release (0.7.1), it does not show up in the supporting files, e.g. aircraftlist.lua.  Should it and, if so, would you like me to update those files?

Thanks,
Paul

**Comment by pdmarsh** [comment]
Hi Ian,

I only just now noticed that my e-mail below went to a “no reply” address (dcs-bios/dcs-bios).  I have a feeling you never got this.  I sent another e-mail to that same address which I’ll resend after this.

In any case, it’s been some time since DCS-BIOS has been updated and I wanted to check in with you on this.  I completely understand that as a hobby you might simply not have interest any longer in supporting DCS-BIOS.  You might have seen that we have started to release DCSFlightpanels along with new DCS-BIOS profiles and explain where to put them.  We’re about to do another such release.  Soon, we’ll start work on yet another.  I am concerned with this for two reasons.  First, there is risk of getting out of sync with official releases of DCS-BIOS that might yet come.  Second, if DCS-BIOS is no longer going to get official updates, these profiles are only being made available to DCSFlightpanels users and not the general sim community that is using DCS-BIOS in other ways.

If you have decided that it’s time to move on from DCS-BIOS, I would like to start posting DCS-BIOS profiles for others to use and will provide instructions on where to put the associated files.  If you would, just let me know where things stand.

Thanks,
Paul

**Pull request closed without merging**
