### PR TITLE
Update tutorial and examples in user guide to latest control references

### PR DESCRIPTION
**Pull request by ericedelman-gh**
It is currently not clear that the tutorial in the user guide is specifically for the A10-C. Also, the Master Caution LED does not work, because the control reference has changed. Other examples throughout the guide have similarly become outdated.

### CODE REVIEW

**Comment by WarLord211** [comment]
Hi
its more an issue than a pull request
anyway master caution from the A-10C work withou problems. Button / LED. tested via control reference.
(installed in vivaldi, BIOS version 0.7.25)
in this BIOS version under DOC are the same pages like on the website.
a copy from the page found here:
https://web.archive.org/web/20181107213043/http://dcs-bios.a10c.de/

**Comment by ericedelman-gh** [comment]
Yes, the A-10C functions work fine when using the control references in the documentation. I'm saying the examples in the user guide are wrong, so this pull request fixes that. It's frustrating for new users to follow an introductory tutorial and not have it work.

By the way, am I contributing to the right project here? I'd love to help out with DCS BIOS, but it seems the DCSFlightpanels fork is much more active. Any reason those changes aren't being merged into the original project?

**Comment by WarLord211** [comment]
The guy is not active in the last month's. And jerker have made the fork for his flightpanels. I needed a bios for the f5 so I made one and merged in jerkers bios. And so we started to integrate as many planes as possible. So this is the reason our fork is active. If you have changes, we will integrate it in our fork. 
Me and jerker using only the bios files for the flight panels. So with anduino our knowledge is limited. We have a discord here we can discuss changes or additions. 
https://discord.gg/5svGwKX

**Comment by ericedelman-gh** [comment]
Thanks very much for the explanation. I'll add my pull request to your fork then. Maybe someday all the improvements will be pulled back into the main project.

**Comment by WarLord211** [comment]
i have integraded you userguide.adoc in our repo

**Comment by ericedelman-gh** [comment]
Cool, thanks. Here's the updated html file too. The original repository doesn't include them, but yours does, so I guess it would be nice to keep the adoc and html files in sync.

The file is just zipped to allow uploading here to github.
[userguide.zip](https://github.com/dcs-bios/dcs-bios/files/3026630/userguide.zip)

**Comment by WarLord211** [comment]
Done! i changed the optic a little bit to match the orginal one.

**Pull request closed without merging**
